config/routes.rb
GoalSetterApp::Application.routes.draw do
  resources :users
  resource :session
  resources :goals
end

app/models/goal.rb
class Goal < ActiveRecord::Base

  validates :user_id, :body, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :goals

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user
      return user if user.is_password?(password)
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

def current_user
  @current_user ||= User.find_by_session_token(session[:session_token])
end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def block_private_goal_page

    if current_user.nil?
      redirect_to new_session_url
    elsif (current_user.id != Goal.find(params[:id]).user_id) && Goal.find(params[:id]).private
      redirect_to user_url(Goal.find(params[:id]).user_id)
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :block_private_goal_page, only: [:show]
  def create
    goal = Goal.new(goal_params)
    goal.user_id = current_user.id
    if goal.save
      redirect_to user_url(goal.user_id)
    else
      flash.now[:error] = goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end
  def show
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:error] = @goal.errors.full_messages
      redirect_to user_url(@goal.user_id)
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to user_url(goal.user_id)
  end

  private
  def goal_params
    self.params.require(:goal).permit(:body, :private, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to user_url(user.id)
    else
      flash[:error] = ["Invalid credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
      @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      sign_in(user)
      redirect_to user_url(user.id)
    else
      flash[:error] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input type="hidden" name="authenticity_token" value=#{form_authenticity_token}>
    HTML

  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
Edit Goal
<form action="<%= goal_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">
<label>Body
<input type="text" name="goal[body]" value="<%= @goal.body %>" >
</label>
<input type="hidden" name="goal[private]" value="false">
<label>Private:
<input type="checkbox" name="goal[private]" value="true" <%= "checked" if @goal.private %> >
</label>
<label>Completed:
  <input type="hidden" name="goal[completed]" value="false" >
<input type="checkbox" name="goal[completed]" value="true" <%= "checked" if @goal.completed %>>
</label>

<button>Update</button>
</form>

app/views/goals/new.html.erb
Create Goal
<form action="<%= goals_url %>" method="post">
<%= auth_token %>

<label>Body
<input type="text" name="goal[body]">
</label>
<label>Private:
  <input type="hidden" name="goal[private]" value="false">
<input type="checkbox" name="goal[private]" value="true" >
</label>
<label>Completed:
  <input type="hidden" name="goal[completed]" value="false">
<input type="checkbox" name="goal[completed]" value="true" >
</label>

<button>Create Goal</button>
</form>

app/views/goals/show.html.erb
<%= @goal.body %><br>
<% if @goal.completed %>
<li>Completed</li>
<br>
<% end %>
<a href=<%= edit_goal_url(@goal.id) %>>Edit</a>

<form action="<%= goal_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <button>Delete</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>

</head>
<body>
  <% unless flash[:error].nil? %>
  <p><%= flash[:error] %></p>
  <% end %>
  <% unless current_user.nil? %>
  <%= current_user.username %>
  <form action="<%=session_url%>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Sign Out">
  </form>
  <hr>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
Sign Up
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Username
  <input type="text" name="user[username]">
</label>
<label>Password:
<input type="password" name="user[password]">
</label>
<input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1><hr>
<h2>Goals</h2>
<ul>
<% @user.goals.each do |goal| %>
<% unless goal.private && current_user.try(:id) != goal.user_id %>
  <li> <a href="<%= goal_url(goal) %>"><%= goal.body %></a></li>
<% end %>
<% end %>
</ul>
<hr>
<a href="<%= new_goal_url %>">New Goal</a>